name: paymaya
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.4.0
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  logger: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.6
  build_runner: ^2.5.4
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
