// Mocks generated by Mockito 5.4.6 from annotations
// in pay_maya/test/features/wallet/data/repositories/wallet_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:paymaya/features/wallet/data/datasources/wallet_remote_data_source.dart'
    as _i3;
import 'package:paymaya/features/wallet/data/models/transaction_model.dart'
    as _i5;
import 'package:paymaya/features/wallet/data/models/wallet_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWalletModel_0 extends _i1.SmartFake implements _i2.WalletModel {
  _FakeWalletModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [WalletRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWalletRemoteDataSource extends _i1.Mock
    implements _i3.WalletRemoteDataSource {
  MockWalletRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WalletModel> getWallet() =>
      (super.noSuchMethod(
            Invocation.method(#getWallet, []),
            returnValue: _i4.Future<_i2.WalletModel>.value(
              _FakeWalletModel_0(this, Invocation.method(#getWallet, [])),
            ),
          )
          as _i4.Future<_i2.WalletModel>);

  @override
  _i4.Future<List<_i5.TransactionModel>> getTransactions() =>
      (super.noSuchMethod(
            Invocation.method(#getTransactions, []),
            returnValue: _i4.Future<List<_i5.TransactionModel>>.value(
              <_i5.TransactionModel>[],
            ),
          )
          as _i4.Future<List<_i5.TransactionModel>>);

  @override
  _i4.Future<void> sendMoney(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#sendMoney, [amount]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
